### ISSUE TITLE
Tested on iOS, Great!

### ISSUE THREAD

**Issue by orangeagain** [sableangle/UnityHTTPServer#3]
Awosome library!
Found a little bug, is that "StreamingAsset" read Permission.
Change "SimpleHTTPServer.cs" Line 321 to ReadOnly can fix it
`Stream input = new FileStream(filename, FileMode.Open,FileAccess.Read);`

**Comment by orangeagain** [comment]
please check this pull
https://github.com/sableangle/UnityHTTPServer/pull/4

**Comment by sableangle** [comment]
The pull is merged, thank you!
